# Site settings
baseurl = "http://my-awesome-site.com/"
languageCode = "en-us"
title = "Hugo Freelancer Theme"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Sophie Touchet"
    description = "Sophie Touchet's portfolio"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "sophietoutchet94@gmail.com"

    [params.navigation]
        brand = "Sophie Touchet"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Sophie Touchet"
        subtitle = "Interior Designer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I am anxious to become a creator. I understand that designing the interior is very important whether itâ€™s a home, school, office or any other building as it makes a place look unique and fit for purpose. I wish to help people to live and work in appropriate and attractive spaces. I believe I can achieve that through hard work, great effort and devoting a sufficient amount of time. That is why I have chosen interior design."
        right = "My acquaintance with art began when I entered Visual and Media Arts School in 2011. During my studies, I dealt with different forms of art and eventually I discovered interior design. After graduating, I decided to concentrate on my modeling career that brought me around the world. This experience initiated in me this eagerness to design through teamwork. Since 2015, I studied an Interior Design Training Program at Herzing College Montreal."

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Copyright 2016"

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["3481 Melrose Place", "Beverly Hills, CA 90210"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-instagram"
                link = "//instagram.com/sosoalice"

            [[params.footer.social.networks]]
                icon = "fa-envelope"
                link=  "mailto:sophietoutchet94@gmail.com"


        [params.footer.credits]
            title = "Credit"
            text = "Portrait by [Benjamin Edward](http://www.benjaminedward.ca)<br/>Maintained by [Antoine Racine](https://github.com/BinaryTiger)"
